name: pytest
on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    types: [opened]
  
jobs:

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        run: |
          git clone https://github.com/LuckyZhangWeiwei/github-actions-python-master.git
          cd github-actions-python-master
      - name: install pytest
        run: |
          pip install pytest
      - name: run pytest
        run: |
          pytest